services:
  frontend:
    container_name: grande-horse
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    networks:
      - app-network

  backend:
    container_name: grande-horse-server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: app-network
