services:
  frontend:
    container_name: grande-horse
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    network_mode: host

  backend:
    container_name: grande-horse-server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    network_mode: host
