services:
  frontend:
    container_name: grande-horse
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    networks:
      - app-network

  backend:
    container_name: grande-horse-server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DB_URL: jdbc:mysql://grande-horse-mysql:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  mysql:
    image: mysql:8.0.40
    container_name: grande-horse-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/datas/mysql-db:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: grande-horse-redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - /home/ubuntu/datas/redis-db:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
